var Babynews={};Babynews.settings={};Babynews.ListManagers={};Babynews.selectors={};Babynews.tags=[];Babynews.separators=[];
Babynews.init=function(){Babynews.ga=new _IG_GA("UA-8912978-1");Babynews.settings.enableSearch=!jQuery.browser.msie;Babynews.settings.TARGET_PAGE_NUM=2;Babynews.settings.layoutIndex=3;Babynews.settings.layoutSet=[{rows:2,columns:2},{rows:3,columns:2},{rows:3,columns:3},{rows:3,columns:4},{rows:4,columns:4}];var a=navigator.userAgent.toLowerCase(),c=a.match(/(iphone|ipod)/);a=a.match(/ipad/);if(c)Babynews.settings.layoutIndex=0;if(a)Babynews.settings.layoutIndex=1;Babynews.settings.RETRY_ATTEMPTS=
5;Babynews.settings.RETRY_WAIT_SECS=10;Babynews.settings.REFRESH_ON=true;Babynews.settings.FIRST_RUN=true;Babynews.settings.SHOW_SCORE=false;Babynews.settings.BASE_URL="http://puddleplaynews.appspot.com";Babynews.settings.SECURE_BASE_URL="https://puddleplaynews.appspot.com";Babynews.settings.SERVER_URL=Babynews.settings.BASE_URL+"/babynews?";Babynews.settings.POSTS_URL=Babynews.settings.SERVER_URL+"getPosts=1&listName=";Babynews.settings.TAGS_LIST_URL=Babynews.settings.SERVER_URL+"getTags=1";Babynews.settings.POST_IMAGE_URL=
Babynews.settings.SERVER_URL+"imagekey=";Babynews.settings.EMAIL_URL=Babynews.settings.SECURE_BASE_URL+"/babynews?sendPost";Babynews.settings.GADGET_IMAGE_URL=Babynews.settings.BASE_URL+"/gadget/images/";Babynews.settings.GADGET_SOURCE_URL=Babynews.settings.BASE_URL+"/gadget/source/";Babynews.settings.postBackgroundImage=Babynews.settings.GADGET_IMAGE_URL+"grad_bg.png";Babynews.settings.alertIconSmall=Babynews.settings.GADGET_IMAGE_URL+"alert_small.png";Babynews.settings.alertIconLarge=Babynews.settings.GADGET_IMAGE_URL+
"alert_large.png";Babynews.settings.logoSmall=Babynews.settings.GADGET_IMAGE_URL+"ppLogo.png";Babynews.settings.animatedLogo=Babynews.settings.GADGET_IMAGE_URL+"pp_anim.gif";Babynews.settings.defaultImageHeight=100;Babynews.settings.defaultImageWidth=100;Babynews.settings.collapseNav=false;Babynews.settings.newPostImage='<img style="position: absolute;opacity: .75;top: 0px ; margin-left: -9px;" src="'+Babynews.settings.GADGET_IMAGE_URL+'new_post_fat.png" width="65px" height="12px" >';Babynews.settings.updateIntervalSecs=
120;Babynews.settings.newPostSecs=43200;Babynews.settings.hashtags=[];Babynews.settings.facyboxPrefs={imageScale:true,padding:15,zoomOpacity:true,zoomSpeedIn:500,zoomSpeedOut:500,zoomSpeedChange:300,overlayShow:true,overlayColor:"#FFF",overlayOpacity:0.7,enableEscapeButton:true,showCloseButton:true,hideOnOverlayClick:true,hideOnContentClick:true,frameWidth:560,frameHeight:340,callbackOnStart:null,callbackOnShow:null,callbackOnClose:null,centerOnScroll:true};Babynews.settings.verticalTransitionSpeed=
500;Babynews.settings.horizontalTransitionSpeed=700;Babynews.settings.postBoxWidth=35;Babynews.settings.verticalPageSpacer=100;Babynews.settings.horizontalPageSpacer=150;Babynews.settings.listSlideSpeed=300;Babynews.settings.startPageNum=2;Babynews.settings.requestCodes={start:0,update:1,addPage:2,refreshCheck:3};Babynews.updateButtons();Babynews.selectors.tagsLinks="#tagsLinks";Babynews.selectors.alertBox={box:"#alert",link:"#tryAgainLink"};Babynews.selectors.skimmer="#skimmer";Babynews.selectors.pageContainer=
"#articleListContainer";Babynews.selectors.contentPane="#contentPane";Babynews.selectors.buttons={left:".leftButton",leftDisabled:".leftButtonDisabled",right:".rightButton",rightDisabled:".rightButtonDisabled"};Babynews.selectors.buttonActions={".rightButton":function(d){Babynews.pageForward(d)},".leftButton":function(d){Babynews.pageBack(d)}};Babynews.layoutManager=new Babynews.LayoutManager;Babynews.alertManager=new Babynews.AlertManager;Babynews.LoadingSpinner='<img src="http://www.google.com/ig/images/spinner.gif"/>';
Babynews.makeLoadingPage=function(d){return'<div id="loadingPage">'+Babynews.LoadingSpinner+" "+d+"</div>"};Babynews.makeLogoLoadingPage=function(d){return'<div id="logoLoadingPage"><table><tr><td><img width="75px" height="75px" src='+Babynews.settings.animatedLogo+'></td><td height="100%">'+d+" </td></tr></div>"};jQuery(Babynews.selectors.pageContainer).html(Babynews.makeLogoLoadingPage("Welcome to puddleplay news!")).fadeIn("fast");jQuery(Babynews.selectors.buttons.left).live("click",Babynews.selectors.buttonActions[Babynews.selectors.buttons.left]);
jQuery(Babynews.selectors.buttons.right).live("click",Babynews.selectors.buttonActions[Babynews.selectors.buttons.right]);jQuery(window).resize(function(){if(!Babynews.isRefreshing){if(Babynews.layoutManager.postSizeTooBig())Babynews.increaseItemDisplayNum();else Babynews.layoutManager.postSizeTooSmall()?Babynews.decreaseItemDisplayNum():Babynews.refreshLayout();Babynews.setScroll(false)}});jQuery(window).keydown(function(d){d.which==39&&Babynews.pageForward();d.which==37&&Babynews.pageBack();d.which==
38&&Babynews.sectionUp();d.which==40&&Babynews.sectionDown()});Babynews.loadPlugins();Babynews.refreshLayout();Babynews.ga.reportPageview("/Gadget Loaded");ZeroClipboard.setMoviePath("' + Babynews.settings.GADGET_SOURCE_URL + 'ZeroClipboard10.swf");Babynews.fetchData(Babynews.settings.TAGS_LIST_URL,Babynews.receiveTags);Babynews.tagsFailTime=(new Date).getTime()+1E3*Babynews.settings.RETRY_WAIT_SECS};
Babynews.receiveTags=function(a){if(a==null||a.data==null||a.data.tags==null){(new Date).getTime()>Babynews.tagsFailTime&&Babynews.alertManager.tagFail(function(){Babynews.tagsFailTime=(new Date).getTime()+1E3*Babynews.settings.RETRY_WAIT_SECS;Babynews.fetchData(Babynews.settings.TAGS_LIST_URL,Babynews.receiveTags)});jQuery(Babynews.selectors.pageContainer).oneTime(1E3,function(){Babynews.fetchData(Babynews.settings.TAGS_LIST_URL,Babynews.receiveTags)})}else{jQuery(Babynews.selectors.pageContainer).stopTime();
Babynews.alertManager.hide();Babynews.processTags(a.data)}};
Babynews.processTags=function(a){var c=jQuery("#listnav"),d=jQuery("<dl>"),b={},e={},j=a.tags;j.length==0&&j.push({Lists:["What's Hot","Most Recent"]});var k=0;Babynews.delaystart=[];for(var p in j){var l=jQuery('<dt class="content">');k==0&&l.css("margin-top",0);l.html(p);l.click(function(){if(Babynews.settings.collapseNav){if(!$(this).hasClass("active")){$(this).parent("dl").find("dd").slideUp(Babynews.settings.listSlideSpeed).end().find("dt").removeClass("active");$(this).addClass("active").next().slideDown(Babynews.settings.listSlideSpeed)}}else $(this).next().find("li:first").trigger("click")});
d.append(l);b=jQuery('<dd class="content">');e=jQuery("<ol>");var q=j[p];for(var s in q){var g={};g.name=q[s];g.displayName=""+g.name;g.menu={};g.index=Babynews.tags.length;g.ListManager=new Babynews.ListManager(g.name,Babynews.tags.length,Babynews.updatedListData);g.selectorID=g.ListManager.selectorID();Babynews.tags.push(g);var n=jQuery("<li>");n.append(g.displayName);n.attr("name",g.name);n.addClass("disabled");n.data("index",g.index);n.click(function(h){var t=jQuery(this);if(!t.hasClass("disabled")){t.parents("dl").find("li.selected").removeClass("selected");
t.addClass("selected");t.removeClass("hover");Babynews.selectTag(jQuery(h.target).data().index)}});n.hover(function(){g=jQuery(this);g.hasClass("disabled")||g.hasClass("selected")||(g.hasClass("hover")?g.removeClass("hover"):g.addClass("hover"))});g.menu.li=n;g.menu.dd=b;g.menu.dt=l;g.menu.dl=d;e.append(n);n=jQuery(Babynews.selectors.pageContainer);var o=jQuery(g.ListManager.getBigPage());n.append(o);if(Babynews.tags.length<3){g.ListManager.fastStart(Babynews.settings.startPageNum*2);g.ListManager.refreshLoop();
g.menu.li.removeClass("disabled")}else Babynews.delaystart.push(g)}b.append(e);d.append(b);k++}window.setTimeout(Babynews.timedStart,1E3);if("prefs"in a){a=a.prefs;if("updateIntervalSecs"in a)Babynews.settings.updateIntervalSecs=parseInt(a.updateIntervalSecs);if("newPostSecs"in a)Babynews.settings.newPostSecs=parseInt(a.newPostSecs);if("imadeWidth"in a)Babynews.settings.defaultImageWidth=parseInt(a.imageWidth);if("imadeHeight"in a)Babynews.settings.defaultImageHeight=parseInt(a.imageHeight);if("hashtags"in
a)Babynews.settings.hashtags=a.hashtags}c.append(d);c.show();c.find("dd").slideUp(1).end();c.find("dd").slideDown(Babynews.settings.listSlideSpeed).end();if(d.height()>Babynews.layoutManager.getPageHeight())Babynews.settings.collapseNav=true;d.css("bottom",d.css("top"));jQuery("listStats").everyTime(6E4,"statsRefresher",Babynews.updateStatsString(false));Babynews.settings.enableSearch&&jQuery.getScript("http://www.google.com/jsapi?key=ABQIAAAA4YutqqGpdQ3P_sKY_kQIVBSt-lvDJx8wPzTLvzz2Zct2Fomc0xQwuMcPeZiy9K0kiL_vHMgPPGhuQQ",
function(){google.load("search","1",{language:"en",callback:Babynews.addSearch})});if(Babynews.tags.length>0){Babynews.settings.listSlideSpeed=0;Babynews.tags[0].menu.li.trigger("click");Babynews.tags[0].menu.dt.trigger("click");Babynews.settings.listSlideSpeed=400}};
Babynews.timedStart=function(){window.setTimeout(function(){var a=Babynews.delaystart.shift();if(a!=null){a.ListManager.fastStart(Babynews.settings.startPageNum);a.ListManager.refreshLoop()}Babynews.delaystart.length>0&&Babynews.timedStart()},100)};
Babynews.selectTag=function(a){if(a!=null)if(!(a>Babynews.tags.length-1)){a=Babynews.tags[a];Babynews.refreshLayout();var c=Babynews.layoutManager;Babynews.hideSearch();Babynews.hideNewPosts();Babynews.clearLoadingIndicator();var d=-1*(c.getPageHeight()+Babynews.settings.verticalPageSpacer),b=1*(c.getPageHeight()+Babynews.settings.verticalPageSpacer);c=d;var e=jQuery(a.selectorID),j=Babynews.settings.verticalTransitionSpeed;if(Babynews.currentTag!=null){jQuery("#logoLoadingPage").remove();c=Babynews.currentTag.index<
a.index?d:b;if(Babynews.currentTag.index==a.index)c=0;d=jQuery(Babynews.currentTag.selectorID);d.css("z-index",-1);d.stop(true,true).animate({top:c},j,"easeInOutQuad",function(){});Babynews.ga.reportEvent("Navigation","Tag Selected",a.name)}else j=0;Babynews.currentTag=a;Babynews.currentListManager=a.ListManager;e.css("top",-1*c);e.css("z-index",100);e.stop(true,true).animate({top:0},j,"easeInOutQuad",function(){});if(Babynews.layoutManager.postSizeTooBig())Babynews.increaseItemDisplayNum();else Babynews.layoutManager.postSizeTooSmall()&&
Babynews.decreaseItemDisplayNum();Babynews.setScroll(false);Babynews.updateButtons();Babynews.updateStatsString(true)}};Babynews.updateStatsString=function(){jQuery(".statsString").hasClass("newPosts")||jQuery(".statsString").html(Babynews.currentTag==null?"":Babynews.currentTag.ListManager.getStatsString())};
Babynews.increaseItemDisplayNum=function(){if(Babynews.settings.layoutIndex<Babynews.settings.layoutSet.length-1){Babynews.settings.layoutIndex++;Babynews.changeItemDisplayNum(Babynews.currentListManager)}else Babynews.settings.layoutIndex=Babynews.settings.layoutSet.length-1};Babynews.decreaseItemDisplayNum=function(){if(Babynews.settings.layoutIndex>0){Babynews.settings.layoutIndex--;Babynews.changeItemDisplayNum(Babynews.currentListManager)}else Babynews.settings.layoutIndex=0};
Babynews.changeItemDisplayNum=function(a){jQuery(Babynews.selectors.pageContainer).fadeOut(200,function(){Babynews.isRefreshing=true;jQuery(Babynews.selectors.contentPane).append(Babynews.makeLoadingPage("Adjusting...")).fadeTo(1E3,0.5);a.repaginate();Babynews.setPageHTMLContents(a);Babynews.refreshLayout();jQuery(Babynews.selectors.pageContainer).fadeIn(200,function(){Babynews.isRefreshing=false;jQuery("#loadingPage").remove();jQuery(Babynews.selectors.contentPane).fadeTo(0,1)})})};
Babynews.pageForward=function(){if(Babynews.currentTag.ListManager.nextPage()){Babynews.setScroll(true);Babynews.updateButtons();Babynews.ga.reportEvent("Navigation","Page Turn",Babynews.currentTag.name,Babynews.currentListManager.getCurrentPageNumber());return true}return false};
Babynews.pageBack=function(){if(Babynews.currentTag.ListManager.previousPage()){Babynews.setScroll(true);Babynews.updateButtons();Babynews.ga.reportEvent("Navigation","Page Turn",Babynews.currentTag.name,Babynews.currentListManager.getCurrentPageNumber());return true}return false};Babynews.sectionUp=function(){Babynews.currentTag.index>0?Babynews.tags[Babynews.currentTag.index-1].menu.li.trigger("click"):Babynews.tags[Babynews.tags.length-1].menu.li.trigger("click")};
Babynews.sectionDown=function(){Babynews.currentTag.index<Babynews.tags.length-1?Babynews.tags[Babynews.currentTag.index+1].menu.li.trigger("click"):Babynews.tags[0].menu.li.trigger("click")};
Babynews.setScroll=function(a){var c=jQuery(Babynews.currentTag.selectorID),d=Babynews.settings.horizontalTransitionSpeed,b=Babynews.layoutManager.getPageScrollOffset(Babynews.currentListManager.getCurrentPageNumber());if(a==null)a=true;a?c.stop().animate({marginLeft:b},d,"easeInOutQuad",Babynews.checkAddPage):c.css("margin-left",b)};Babynews.checkAddPage=function(){if(Babynews.currentListManager.lastPage()){Babynews.currentTag.ListManager.addAnotherPage(2);Babynews.showLoadingIndicator()}};
Babynews.showLoadingIndicator=function(){jQuery("#loadingIndicator").html(" Loading more posts...").fadeIn(400)};Babynews.hideLoadingIndicator=function(){jQuery("#loadingIndicator").fadeOut(400).html("")};Babynews.clearLoadingIndicator=function(){jQuery("#loadingIndicator").fadeOut(1).html("")};Babynews.pageAddProcessing=function(){jQuery("#loadingIndicator").fadeOut(250).html(Babynews.LoadingSpinner+" Processing posts...").fadeIn(400)};
Babynews.showNewPosts=function(a,c,d){if(d.length==0||a!==Babynews.currentListManager)return false;for(var b=false,e=a.getCurrentPageNumber();e>=0;e--)if(c[e])b=true;if(!b)return false;b=jQuery(".statsString");if(!b.hasClass("newPosts")){b.addClass("newPosts");b.data("newPosts",{lm:a,diff:c,newPosts:d});b.click(function(){var j=jQuery(".statsString").data("newPosts");Babynews.updatedListData(j.lm,j.diff,j.newPosts);Babynews.hideNewPosts();return false});b.hover(function(){jQuery(this).addClass("hover")},
function(){jQuery(this).removeClass("hover")});a=d.length;b.html("We just found "+a+" new "+(a>1?"posts":"post")+"! Click to update.")}return true};Babynews.hideNewPosts=function(){var a=jQuery(".statsString");a.removeClass("newPosts");a.unbind("click");a.removeClass("hover");Babynews.updateStatsString(false)};Babynews.newPages=function(a,c){if(a!=null){jQuery(Babynews.tags[a.index].menu.li).removeClass("disabled");Babynews.setPageHTMLContents(a,c);Babynews.updateButtons();Babynews.hideLoadingIndicator()}};
Babynews.updatedListData=function(a,c,d){if(a!=null){Babynews.setPageHTMLContents(a,c,d);Babynews.updateStatsString(false)}};
Babynews.setPageHTMLContents=function(a,c,d){for(var b=jQuery(a.selectorID()),e=0;e<a.getNumPages();e++)if(!(c!=null&&!c[e])){var j=a.getPageElement(e),k=b.find("#page"+String(e));k.length==0?b.append(j):k.replaceWith(j);k=b.find("#page"+String(e));k.find(".imageLoading").each(function(){jQuery(this).attr("src",jQuery(this).attr("source"))});Babynews.fixTextPage(a);k.find(".headlineAnalytics").click(function(l){var q=jQuery(l.target).attr("title");l=jQuery(l.target).attr("blog");Babynews.ga.reportEvent("Post Click",
"Headline",l+" : "+q)});k.find(".imageAnalytics").click(function(l){var q=jQuery(l.target).attr("title");l=jQuery(l.target).attr("blog");Babynews.ga.reportEvent("Post Click","Image",l+" : "+q)});k.find(".blogAnalytics").click(function(l){l=jQuery(l.target).html();Babynews.ga.reportEvent("Post Click","Blog",l)})}b=jQuery(a.selectorID());b.attr("num",a.getNumItemsPerPage());for(var p in d)jQuery(b.find("[key='"+String(d[p].key)+"']")).fadeTo(0,0,function(){jQuery(this).fadeTo(800,1)})};
Babynews.addSearch=function(){var a=jQuery('<dt class="content">');a.html("Search");var c=jQuery("#listnav").find("dl");c.append(a);a=jQuery('<dd class="content">');a.html('<div id="navSearch">');c.append(a);c=jQuery("<div>");c.css("z-index",-1).attr("id","searchContainer").addClass("shrinkWrap").css("marginRight",0).css("marginLeft",0).css("left",0);a=jQuery("<div>");a.addClass("page");a.css("background-color","white");var d=jQuery("<div>").attr("id","searchResultsBoxTop").addClass("closeLink").css("width",
"100%").css("text-decoration","none");d.append('<a  href="" onclick="Babynews.hideSearch()"><< Go back to puddleplay news</a>');a.append(d);jQuery("<div>").attr("id","navSearch");a.append(d);d=jQuery("<div>");d.attr("id","searchResults");a.append(d);d=jQuery("<div>").addClass("closeLink").css("width","100%").css("text-decoration","none");d.append('<a href="" onclick="Babynews.hideSearch()"><< Go back to puddleplay news</a>');a.append(d);c.append(a);jQuery(Babynews.selectors.pageContainer).append(c);
c=new google.search.CustomSearchControl("013974144322735817659:wnhkdrzkmtw");a=new google.search.SearcherOptions;a.setExpandMode(google.search.SearchControl.EXPAND_MODE_OPEN);c.addSearcher(new google.search.WebSearch,a);c.setResultSetSize(google.search.Search.SMALL_RESULTSET);a=new google.search.DrawOptions;a.setSearchFormRoot("cse");a.setSearchFormRoot("navSearch");a.setDrawMode(google.search.SearchControl.DRAW_MODE_LINEAR);c.draw("searchResults",a);c.setSearchStartingCallback(this,Babynews.onSearchComplete);
d=$("table.gsc-search-box").find("td");c=$("<table>").addClass("gsc-search-box").append("<tbody>");a=$("<tr>").append($(d[0])).attr("align","right");d=$("<tr>").append($(d[1])).attr("align","right");c.append(a).append(d);$("table.gsc-search-box").replaceWith(c);$("#navSearch").parent("dd").slideDown(Babynews.settings.listSlideSpeed).end();Babynews.hideSearch()};
Babynews.hideSearch=function(){var a=jQuery("#searchContainer"),c=Babynews.settings.verticalTransitionSpeed*0.75,d=Babynews.layoutManager;a.stop(true,true).animate({left:d.getPageWidth()*-1.2},c,"easeInOutQuad",function(){jQuery(this).css("z-index",-1)});jQuery(".navBar").fadeTo("fast",1)};
Babynews.onSearchComplete=function(a){var c="";if(a!=null&&"Cc"in a)c=a.Cc;c.length>0&&Babynews.ga.reportEvent("Search","initiated",c);a=jQuery("#searchContainer");c=Babynews.settings.verticalTransitionSpeed*1.5;a.css("z-index",1E3);a.stop(true,true).animate({left:0},c,"easeInOutQuad",function(){});jQuery(".navBar").fadeTo("fast",0)};
Babynews.updateButtons=function(){if(Babynews.currentListManager!=null){var a=true,c=true;if(Babynews.currentListManager){a=Babynews.currentListManager.firstPage();c=Babynews.currentListManager.lastPage()}jQuery(Babynews.selectors.buttons.left).show();jQuery(Babynews.selectors.buttons.right).show();jQuery(Babynews.selectors.buttons.leftDisabled).show();jQuery(Babynews.selectors.buttons.rightDisabled).show();a?jQuery(Babynews.selectors.buttons.left).hide():jQuery(Babynews.selectors.buttons.left).show();
a?jQuery(Babynews.selectors.buttons.leftDisabled).show():jQuery(Babynews.selectors.buttons.leftDisabled).hide();c?jQuery(Babynews.selectors.buttons.right).hide():jQuery(Babynews.selectors.buttons.right).show();c?jQuery(Babynews.selectors.buttons.rightDisabled).show():jQuery(Babynews.selectors.buttons.rightDisabled).hide()}};Babynews.fixTextPage=function(a){for(var c=a.getNumPages(),d=0;d<c;d++){var b=jQuery(a.selectorID()+" #page"+String(d));Babynews.fixTextItem(a,b)}};
Babynews.fixTextItem=function(a,c){for(var d=jQuery(".post",c),b=0;b<a.getNumItemsPerPage();b++){var e=jQuery(d[b]);e.attr("item");e.attr("page");var j=e.find(".image");j.css("width","");j.css("height","");content_height=Babynews.layoutManager.getContentHeight();j=e.find(".fixContentText");j.html();var k=a.getPostDatabyKey(e.attr("key"));if(k==null)return;var p=true;if(k!=null)p=jQuery.inArray("image",k.flags)>-1;Babynews.trimtoRect2(j,j.width(),content_height,"...",true,false,k);j=e.find(".fixHeadlineText");
e=j.parent().width();var l=Babynews.layoutManager.getHeadlineHeight();Babynews.trimtoRect2(j,e,p?l:l*1.25,"...",true,false,k)}};
Babynews.ListManager=function(a,c,d){this.name=a;this.index=c;this.list=[];this.keys={};this.url=Babynews.settings.POSTS_URL+this.name.replace(/ /ig,"%20");this.doneCallback={};this.refresher=d;this.stats={numPosts:0,updated_string:"",updated_posts:0,numSources:0,refreshed:0};this.book={currentPage:0,pagelength:0,numpages:0,numitemstotal:0,pages:[],htmlPages:[]};this.updateIntervalSecs=Babynews.settings.updateIntervalSecs;this.newPostSecs=Babynews.settings.newPostSecs;this.targetPagenum=Babynews.settings.TARGET_PAGE_NUM;
this.numChars=600;this.book.pages=[];this.book.htmlPages=[];this.book.newPosts=[];this.requestIDs=[];this.selectorID=function(){return"#"+this.name.replace(/ /ig,"_").replace(/'/ig,"")};this.selectorName=function(){return this.name.replace(/ /ig,"_").replace(/'/ig,"")};this.getListSubset=function(b,e){for(var j=[],k=b;k<this.list.length&&k<e;k++)j.push(this.list[k]);return j};this.checkup=function(){if(!this.hasHTMLPage(0))return"bad";if(this.requestIDs.length>=this.targetPagenum)return"bad";if(this.book.htmlPages.length<
this.targetPagenum)return"ok";if(this.book.htmlPages.length==this.targetPagenum)return"good"};this.getStatsString=function(){if(this.stats.refreshed<100)return"";var b="Last updated: "+Babynews.prettyDate((new Date).getTime()-this.stats.refreshed);if(this.stats.numSources>1)b+=" from "+this.stats.numSources+' <a class="sitesLink" href="http://www.puddleplay.com/news/sites" target="_blank">sites</a>.';return b};this.getPostDatabyKey=function(b){for(var e=null,j=0;j<this.list.length;j++)if(this.list[j].key==
b){e=this.list[j];break}return e};this.containsPostKey=function(b){return this.getPostDatabyKey(String(b))==null?false:true};this.getNumItemsPerPage=function(){var b=Babynews.settings.layoutSet[Babynews.settings.layoutIndex];return b.rows*b.columns-1};this.repaginate=function(b){this.book.numitemstotal=this.list.length;this.book.pagelength=this.getNumItemsPerPage();this.book.numpages=Math.ceil(this.list.length/this.book.pagelength);for(var e=0;e<this.book.numpages;e++){this.book.pages[e]=this.getListSubset(e*
this.book.pagelength,(e+1)*this.book.pagelength);if(b==null||b[e])this.book.htmlPages[e]=this.makePageElement(e)}if(this.book.currentPage>this.book.numpages)this.book.currentPage=this.book.numpages-1};this.getBigPage=function(){var b=jQuery("<div>");b.attr("id",this.selectorName());for(var e=0;e<this.book.numpages;e++){var j=this.book.htmlPages[e];if(j==null)j=this.makePageElement(e);b.append(j)}b.addClass("shrinkWrap");b.css("marginRight",-4500);b.css("marginLeft",0);b.css("top",Babynews.layoutManager.getPageHeight()+
Babynews.settings.verticalPageSpacer);b.css("z-index",-1);b.attr("index",this.index);return b};this.hasHTMLPage=function(b){if(b==null)b=0;return this.book.htmlPages.length>0&&this.book.htmlPages[b]!=null?true:false};this.getPageElement=function(b){var e=this.book.htmlPages[b];if(e==null)e=this.makePageElement(b);return e};this.makePageElement=function(b){var e=jQuery("<div>");e.attr("id","page"+String(b));e.css("float","left");e.css("display","block");e.css("margin-right",Babynews.settings.horizontalPageSpacer+
"px");e.attr("num",this.getNumItemsPerPage());e.addClass("page");b<this.book.numpages&&e.append(Babynews.getPageHTML(this.book.pages[b],b,this));return e};this.getCurrentPageElement=function(){return this.getPageElement(this.book.currentPage)};this.getPage=function(b){if(this.book.numpages==null||b>this.book.numpages)return[];return this.book.pages[b]};this.nextPage=function(){if(this.book.currentPage<this.book.numpages-1){this.book.currentPage++;return true}else return false};this.previousPage=function(){if(this.book.currentPage>
0){this.book.currentPage--;return true}else return false};this.firstPage=function(){return this.book.currentPage==0?true:false};this.lastPage=function(){return this.book.currentPage==this.book.numpages-1?true:false};this.getCurrentPageData=function(){return this.getPage(this.book.currentPage)};this.getCurrentPageNumber=function(){return this.book.currentPage};this.getNumPages=function(){return this.book.numpages>0?this.book.numpages:0};this.fastStart=function(b){this.fetchData({ID:Math.random()*10,
reqTime:(new Date).getTime(),pages:b,doneCallback:Babynews.newPages,ListManager:this,code:Babynews.settings.requestCodes.start})};this.refreshAll=function(){this.fetchData({ID:Math.random()*10,reqTime:(new Date).getTime(),pages:this.targetPagenum,doneCallback:Babynews.updatedListData,ListManager:this,code:Babynews.settings.requestCodes.update})};this.checkForUpdate=function(){this.fetchData({ID:Math.random()*10,reqTime:(new Date).getTime(),pages:0,doneCallback:null,ListManager:this,code:Babynews.settings.requestCodes.refreshCheck})};
this.addAnotherPage=function(b){b=b==null?1:b;this.fetchData({ID:Math.random()*10,reqTime:(new Date).getTime(),pages:this.targetPagenum+b,numAdded:b,doneCallback:Babynews.newPages,ListManager:this,code:Babynews.settings.requestCodes.addPage})};this.refreshLoop=function(){jQuery(this.selectorID()).stopTime(this.name);var b=this.updateIntervalSecs*1E3+Math.random()*5E3;jQuery(this.selectorID()).everyTime(b,this.name,function(){if(Babynews.settings.REFRESH_ON){var e=parseFloat(jQuery(this).attr("index"));
Babynews.tags[e].ListManager.checkForUpdate()}})};this.stopRefresh=function(){jQuery(this.selectorID()).stopTime(this.name)};this.fetchData=function(b){if(b.pages==null)b.pages=this.targetPagenum;var e=0;if(b.code==Babynews.settings.requestCodes.addPage)e=b.pages-b.numAdded;var j=b.pages*this.getNumItemsPerPage();this.requestIDs.push(b);b=[this.url,"&start=",e,"&end=",j,"&contentLength=",this.numChars,"&ID=",b.ID].join("");Babynews.fetchData(b,Babynews.megaMegaCallback)};this.popID=function(b){for(var e=
0;e<this.requestIDs.length;e++)if(this.requestIDs[e].ID==b)return this.requestIDs.splice(e,1);return null};this.storePost=function(b){this.list[i]=b};this.processList=function(b,e){var j=this.popID(b);if(j==null)return false;j=j[0];var k=-1,p=parseInt(j.code),l={};if("stats"in e){l=e.stats;if("numSources"in l)this.stats.numSources=parseInt(l.numSources);if("tag"in l)this.stats.tag=l.tag;if("refreshed"in l)this.stats.refreshed=parseFloat(l.refreshed);if("updated_posts"in l){k=parseInt(l.updated_posts);
(new Date).getTime()}}if(p==Babynews.settings.requestCodes.refreshCheck)if(k==this.stats.updated_posts)return;else this.refreshAll();if(p==Babynews.settings.requestCodes.addPage){var q=parseInt(j.pages),s=j.numAdded;l=[];var g=0;g=this.targetPagenum*this.getNumItemsPerPage();q=q*this.getNumItemsPerPage();for(var n=g;n<q;n++)if(String(n)in e){g=Math.floor(n/this.getNumItemsPerPage());var o=e[String(n)];o.post_title="post_title"in o?jQuery.base64Decode(o.post_title):"";o.blog_title="blog_title"in o?
jQuery.base64Decode(o.blog_title):"";o.post_content="post_content"in o?jQuery.base64Decode(o.post_content):"";if(this.list[n]==null||this.list[n].key!=o.key)l[g]=true;this.list[n]=o}this.targetPagenum+=s;this.repaginate(l);j.doneCallback(this,l)}if(p==Babynews.settings.requestCodes.start){q=parseInt(j.pages);l=[];for(n=0;n<q*this.getNumItemsPerPage()+1;n++)if(String(n)in e){g=Math.floor(n/this.getNumItemsPerPage());o=e[String(n)];o.post_title="post_title"in o?jQuery.base64Decode(o.post_title):"";
o.blog_title="blog_title"in o?jQuery.base64Decode(o.blog_title):"";o.post_content="post_content"in o?jQuery.base64Decode(o.post_content):"";l[g]=true;this.list[n]=o}this.repaginate(l);j.doneCallback(this,l)}if(p==Babynews.settings.requestCodes.update){parseInt(j.pages);l=[];p=[];s=[];for(n=0;n<this.targetPagenum*this.getNumItemsPerPage();n++)if(String(n)in e){o=e[String(n)];if(this.list[n]!=null&&this.list[n].key==o.key)s[n]=this.list[n];else{g=Math.floor(n/this.getNumItemsPerPage());o.post_title=
"post_title"in o?jQuery.base64Decode(o.post_title):"";o.blog_title="blog_title"in o?jQuery.base64Decode(o.blog_title):"";o.post_content="post_content"in o?jQuery.base64Decode(o.post_content):"";if(this.list[n]==null||this.list[n].key!=o.key)l[g]=true;this.containsPostKey(o.key)||p.push({page:g,key:o.key});s[n]=o}}if(l.length>0){this.list=s;this.repaginate(l);Babynews.showNewPosts(this,l,p)||j.doneCallback(this,l,p)}}this.stats.updated_posts=k;Babynews.updateStatsString();return true}};
Babynews.fetchData=function(a,c){var d=[];d[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON;var b=(new Date).getTime(),e="?";if(a.indexOf("?")>-1)e="&";a=[a,e,"nocache=",b].join("");gadgets.io.makeRequest(a,c,d)};Babynews.megaMegaCallback=function(a){if(!(a==null||a.data==null)){a=a.data;if(a!=null){var c="ID"in a?a.ID:"",d=0;for(;d<Babynews.tags.length;d++)Babynews.tags[d].ListManager.processList(c,a)}}};
Babynews.AlertManager=function(){this.noReplyAttempts=this.noDataAttempts=0;this.duration=300;this.timer={};this.fails=0;this.tryAgainCallback={};this.tagsFail=0;this.topAlert=jQuery("#topAlert");var a=jQuery('<div id="alertContainer" class="shrinkWrap page">'),c=jQuery('<div id="pageAlert" class="alert">'),d=jQuery('<div style="float: right;width: 75%">');c.append('<img src="'+Babynews.settings.alertIconLarge+'">');d.append("<p>We tried and tried, but couldn't connect to our servers.</p>");d.append("<p>We'll be back soon!</p>");
d.append('<p id="tryAgainLink" class="tryAgainLink"> Keep Trying </p>');c.css("opacity",1);c.append(d);a.append(c);a.css("opacity",1);a.css("z-index","1");this.init=function(){this.topAlert.addClass("alert");this.topAlert.append('<span id="topAlertMessage">');var b=jQuery('<span class="trying" style="float:right;">');b.append('<span id="topAlertTrying">');b.append('<span id="topAlertCountdown">');b.append('<span id="topAlertTryAgain" class="tryAgainLink">');this.topAlert.append(b);this.topAlert.hide()};
this.tagFail=function(b){Babynews.alertManager.show();this.tryAgainCallback=b};this.showTopAlert=function(){jQuery("#topAlertMessage").html("Unable to retrieve this list from puddleplay.com ");jQuery("#topAlertTrying").html(" Trying in: ");jQuery("#topAlertTryAgain").html(" |  Try Now ");this.topAlert.fadeIn(this.duration)};this.show=function(){jQuery("#alertContainer").stop(true,true).animate({top:0},1,"easeInOutQuad",function(){});jQuery("#tryAgainLink").live("click",function(){Babynews.alertManager.hide(this.duration);
Babynews.alertManager.tryAgainCallback()})};this.hide=function(){var b=Babynews.layoutManager.getPageHeight()+Babynews.settings.verticalPageSpacer;jQuery("#alertContainer").stop(true,true).animate({top:b},Babynews.settings.verticalTransitionSpeed,"easeInOutQuad",function(){})}};
Babynews.refreshLayout=function(){var a=Babynews.layoutManager;a.recalculate();a=" .shrinkWrap { height:"+a.getPageHeight()+"px;} .shrinkWrap .page { height:"+a.getPageHeight()+"px; width:"+a.getPageWidth()+"px;} .post {height:"+a.getBoxHeight()+"px; width:"+a.getBoxWidth()+"px;} .post.first {width:"+a.getFirstBoxWidth()+"px;}  #contentPane { height:"+a.getPageHeight()+"px;}";var c=document.getElementById("blockSizeStyle");if(c.styleSheet)c.styleSheet.cssText=a;else jQuery(c).html(a)};
Babynews.LayoutManager=function(){this.minBoxWidth=250;this.minBoxHeight=200;this.boxWidth=this.minBoxWidth;this.boxHeight=this.minBoxHeight;this.headlineWidth=this.contentWidth=this.contentHeight=this.headlineHeight=this.pageHeight=this.pageWidth=0;this.headlineWidthPercent=90;this.headlineHeightPercent=25;this.contentWidthPercent=80;this.contentHeightPercent=30;this.peek_offset=0;this.bottomNavOffset=jQuery("bottomNav").height();this.columns=this.rows=0;this.getPageScrollOffset=function(a){this.recalculate();
return-1*a*(this.pageWidth+Babynews.settings.horizontalPageSpacer)};this.recalculate=function(){var a=jQuery(Babynews.selectors.skimmer),c=jQuery(Babynews.selectors.contentPane).width();a=a.height();if(c==0)c=jQuery(window).width();if(a==0)a=jQuery(window).height();var d=Babynews.settings.layoutSet[Babynews.settings.layoutIndex];this.columns=d.columns;this.rows=d.rows;this.pageWidth=c-this.peek_offset;this.pageHeight=a-this.bottomNavOffset;this.boxWidth=Math.floor(this.pageWidth/this.columns);this.boxHeight=
Math.floor(this.pageHeight/this.rows);this.headlineWidth=this.boxWidth*this.headlineWidthPercent*0.01;this.headlineHeight=this.boxHeight*this.headlineHeightPercent*0.01;this.contentWidth=this.boxWidth*this.contentWidthPercent*0.01;this.contentHeight=this.boxHeight*this.contentHeightPercent*0.01};this.postSizeTooSmall=function(){return this.boxWidth*this.boxHeight<this.minBoxHeight*this.minBoxWidth};this.postSizeTooBig=function(){return this.boxWidth*this.boxHeight>this.minBoxHeight*this.minBoxWidth*
1.5};this.getFirstBoxWidth=function(){return this.boxWidth*2};this.getBoxHeight=function(){return this.boxHeight};this.getBoxWidth=function(){return this.boxWidth};this.getPageWidth=function(){return this.pageWidth};this.getPageHeight=function(){return this.pageHeight};this.getNumColumns=function(){return this.columns};this.getNumRows=function(){return this.rows};this.getHeadlineHeight=function(){return this.headlineHeight};this.getContentHeight=function(){return this.contentHeight};this.getContentWidth=
function(){return this.contentWidth};this.getHeadlineWidth=function(){return this.headlineWidth}};
Babynews.getPageHTML=function(a,c,d){var b=[];if(a==null||a.length==0)return Babynews.LoadingPage;for(var e=0;e<a.length;e++)b.push(Babynews.getItemHTML(a[e],e,c));if(c%2==0&&d.getNumItemsPerPage()>=8){e=Math.ceil(Babynews.layoutManager.getNumColumns()+Babynews.layoutManager.getNumColumns()/2);b.splice(e,0,b[0]);b.shift()}a=jQuery("<ul> ");a.addClass("blocks grid");for(e=0;e<b.length;e++)a.append(b[e]);return a};
Babynews.getItemHTML=function(a,c,d){itemHTML="";var b={};if(a==null)a={};b.flags="flags"in a?a.flags:"";var e=jQuery.inArray("twitter",b.flags)>-1,j=jQuery.inArray("newPost",b.flags)>-1,k=jQuery.inArray("image",b.flags)>-1,p=c==0?true:false;b.key="key"in a?a.key:"";b.post_url="post_url"in a?a.post_url:"";b.post_title="post_title"in a?a.post_title:"";b.image="image"in a?a.image:"";b.image_url=Babynews.settings.POST_IMAGE_URL+b.key;b.image_tag=jQuery('<img src="'+b.image_url+'" width='+b.image.w+" height="+
b.image.h+">");b.blog_title="blog_title"in a?a.blog_title:"";b.post_content="post_content"in a?a.post_content:"";b.blog_url="blog_url"in a?a.blog_url:"";b.score="score"in a?a.score:"";b.post_date_ago="post_date_ago"in a?a.post_date_ago:"";var l="post";if(p)l+=" first";a=jQuery("<li>");a.addClass(l);a.attr("page",d);a.attr("item",c);a.attr("key",b.key);l=jQuery('<div class="container fill"> ');var q=jQuery('<div class="content flip">'),s=jQuery(Babynews.settings.newPostImage),g=e?"":" fixHeadlineText ",
n=jQuery("<div>").attr("class","spacer"),o=jQuery(' <div class=" headline "> ');g=jQuery('<a class="headlineAnalytics '+g+'" href="'+b.post_url+'" target="_blank">'+(e?b.blog_title:b.post_title)+"</a>");g.attr("blog",b.blog_title);g.attr("title",b.post_title);o.append(g);if(k){var h="image";if(p)h+=" first";h=jQuery("<div>").addClass(h);g=new Image;jQuery(g).addClass("imageLoading").attr("source",b.image_url).attr("key","image_"+String(b.key)).load(function(){var D=$(this);D.removeClass("imageLoading");
D.fadeIn("fast")}).width(b.image.w).height(b.image.h);var t=jQuery("<a>");t.addClass("imageAnalytics");t.attr("href",b.image_url+"&fullsize=1");t.attr("blog",b.blog_title);t.attr("title",b.post_title);if(e)t=jQuery('<a title="'+b.blog_title+'" href="'+b.blog_url+'" target="_blank"></a>');t.append(g);h.append(t);e||h.attr("onMouseOver","Babynews.addFancybox(event)");h.attr("page",d);h.attr("item",c)}g=35;k||(g=80);if(p)g=200;p={};p=Babynews.trimText(b.blog_title,g,"...");p=b.blog_url!=null&&b.blog_url.length>
0?jQuery('<div class="posted"><a class="blogAnalytics"  href="'+b.blog_url+'" target="_blank"> '+(e?"Twitter":p)+"</a> - "+Babynews.prettyDate(parseFloat(b.post_date_ago))+"</div>"):jQuery('<div class="posted">'+(e?"Twitter":p)+" - "+Babynews.prettyDate(parseFloat(b.post_date_ago))+"</div>");g={};g=e?jQuery('<p class="postContent">'+b.post_title+"</p>"):jQuery('<div class="postContent"><span class="fixContentText">'+b.post_content+'</span><span class="moreLink"><a onClick="Babynews.moreClicked(event)" blog="'+
b.blog_title+'" title="'+b.post_title+'" href="'+b.post_url+'" target="_blank"> more</a></span></div>');b=jQuery("<div>");b.css("position","absolute");b.css("top","-5");b.css("left","5");b.html('<p> <a class="spch-bub-inside" href="#">  <span class="point"></span>    <em>23 Comments</em> </a> </p>');b=jQuery("<div>Share</div>");b.attr("page",d);b.attr("item",c);b.addClass("sharePrompt");b.attr("onClick","Babynews.flipIt(event)");if(e){j&&q.append(s);q.append(n);k&&q.append(h);q.append(o)}else{j&&
q.append(s);q.append(jQuery("<div>").css("height","4px"));q.append(o);k&&q.append(h)}q.append(p);q.append(g);q.append(b);l.append(q);a.append(l);return a};Babynews.trimText=function(a,c,d){if(a.length>c){a=a.substring(0,c);for(c=a.length;a.substr(--c,1)!=" ";);for(;!/[A-Za-z]/.test(a.substr(c-1,1));)--c;a=a.substring(0,c)+d}return a};
Babynews.addFancybox=function(a){a&&a.preventDefault&&a.preventDefault();if(a&&a.stopPropagation)a.stopPropagation();else a.cancelBubble=true;var c={};if(a.target)c=jQuery(a.target).parent();else if(a.srcElement)c=jQuery(a.srcElement).parent();a=Babynews.settings.facyboxPrefs;a.type="image";a.titlePosition="inside";a.orig=c;a.titleFormat=function(){var d=Babynews.currentTag.ListManager.getPostDatabyKey(c.parents("li").attr("key"));return jQuery("<div>").attr("id","fancyboxShare").html(Babynews.sharing.getUI(d,
true))};c.fancybox(a)};
Babynews.flipIt=function(a){var c;if(!a)a=window.event;if(a.target)c=a.target;else if(a.srcElement)c=a.srcElement;a=jQuery(c);var d=Babynews.currentTag.ListManager.getPostDatabyKey(a.parents("li").attr("key"));a.parents(".flip").flip({direction:"lr",speed:220,content:function(){return Babynews.sharing.getUI(d)},color:"#F0F0F0",onEnd:function(){jQuery(".facebookAnalytics").click(function(b){Babynews.ga.reportEvent("Sharing","on Facebook",b.target.href)});jQuery(".twitterAnalytics").click(function(b){Babynews.ga.reportEvent("Sharing","on Twitter",
b.target.href)})}});Babynews.ga.reportEvent("Sharing","Share Opened",d.blog_title+" : "+d.post_title)};
Babynews.sharing={getUI:function(a,c){var d=jQuery("<div>");d.addClass("overlay");d.attr("id","overlay");d.css("visibility","visible");d=jQuery("<div>");d.addClass("shareBox");if(c){d.addClass("shareBoxFloating");d.css("width",280);d.css("height",200);d.css("right",-310);d.css("top",-140)}jQuery.inArray("twitter",a.flags);var b=jQuery("<div>");b.addClass("shareTitle");b.html(Babynews.trimText(a.post_title,65,"..."));var e=jQuery("<div>");e.attr("key",a.key);e.addClass("shareGroup");e.append('<span class="shareGroupLabel" style="color: #D40000">Post</span>');
var j=jQuery('<div class="shareItem"> <a class="facebookAnalytics" name="fb_share" type="icon_link" share_url="'+a.post_url+'" href="http://www.facebook.com/sharer.php">Facebook</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"><\/script> </div>'),k=jQuery('<div class="shareItem"> <a class="twitterAnalytics" href="'+a.post_url+'" target="_blank"><span class="twitterbutton"><span class="twitterShare">Twitter</span></span></a> </div>');Babynews.bitly.shortenURL(a,
k.find("a"),function(l,q,s){var g=l.post_title;l=g+" "+s+" on http://puddleplay.com/news";for(var n=g.length;l.length>140;){for(;g.substr(--n,1)!=" ";);for(;!/[A-Za-z]/.test(g.substr(n-1,1));)n--;l=g.substr(0,n)+"... "+s+" on http://puddleplay.com/news"}for(s=0;s<Babynews.settings.hashtags.length;s++){g="+"+Babynews.settings.hashtags[s];if(l.length+g.length<=140)l+=escape(g)}q.attr("href","http://twitter.com/home?status="+l)});e.append(j);e.append(k);j=jQuery("<div>");j.attr("id","emailGroup");j.addClass("shareGroup");
j.append('<span class="shareGroupLabel" style="color: #00D400">Email</span>');j.append(Babynews.email.getUI(a.key));k=jQuery("<div>");k.attr("key",a.key);k.attr("id","linkBox_"+a.key);k.addClass("shareGroup");k.append('<span class="shareGroupLabel" style="color: #00BBDD">Link</span>');var p=jQuery(Babynews.LoadingSpinner).attr("width",12).attr("height",12);Babynews.bitly.shortenURL(a,p,function(l,q,s){l=q.parent().attr("key");s=jQuery("<input>").attr("id","link_"+l).attr("readonly",true).attr("type",
"text").addClass("shareInput").addClass("bitlyInput").val(s);q.replaceWith(s);q=new ZeroClipboard.Client;q.addEventListener("complete",function(g){var n=jQuery('<span style="font-weight:bold; color:#00BBDD; font-size:14px;"> copied </span>');jQuery(g.domElement).parent().append(n.fadeIn(500,function(){jQuery(this).fadeOut(500)}));jQuery(g.domElement).select()});q.glue("link_"+l,"linkBox_"+l);if(Babynews.clipboardObjects==null)Babynews.clipboardObjects=[];Babynews.clipboardObjects.push({key:l,client:q})});
k.append(p);d.append(b);d.append(e);d.append(j);d.append(k);b=jQuery("<div>close</div>");b.addClass("sharePrompt");b.click(function(l){l&&l.preventDefault&&l.preventDefault();if(l&&l.stopPropagation)l.stopPropagation();else l.cancelBubble=true;l=jQuery(l.target);l.parents(".flip").revertFlip();l.parents("#fancyboxShare").remove();l=l.parents("li").attr("key");for(var q in Babynews.clipboardObjects)if(Babynews.clipboardObjects[q].key==l){match=Babynews.clipboardObjects.splice(q,1)[0];match.client.destroy()}});
d.append(b);b=jQuery("<div>");b.attr("id","sharing");b.css("vertical-align","middle");b.append(d);return b}};
Babynews.email={sendEmail:function(a){a.preventDefault();a=jQuery(a.target).parents("#emailUI");var c=jQuery(this).find("input:hidden[name=key]").val();if(Babynews.email.requests==null)Babynews.email.requests=[];Babynews.email.requests.push({key:c,target:a});c=Babynews.settings.EMAIL_URL+"&"+jQuery(this).serialize();Babynews.fetchData(c,Babynews.email.emailResponse);a.html(Babynews.makeLoadingPage("Sending"))},emailResponse:function(a){if(!(a==null||a.data==null)){var c,d,b,e,j="";if("key"in a.data)c=
a.data.key;if("status"in a.data)d=a.data.status;if("title"in a.data)e=a.data.title;if("blog"in a.data)j=a.data.blog;if("error"in a.data)b=a.data.error;var k=null;for(var p in Babynews.email.requests)if(Babynews.email.requests[p].key==c){k=Babynews.email.requests.splice(p,1)[0];break}if(k!=null){c=k.target;if(d=="ERROR"){e=jQuery("<div>");e.attr("id","emailAlert").addClass("shareAlertBox").addClass("email");"error"in a.data&&e.html("<p>"+b+"</p>");a=jQuery("<div>").addClass("alertButton").html(Babynews.email.strings.errorButton);
e.append(a);c.html(e)}else{b=jQuery("<div>");b.attr("id","emailSuccess").addClass("shareAlertBox").addClass("email");b.html(jQuery("<p>").append(Babynews.email.strings.sendSuccessText));a=jQuery("<div>").addClass("alertButton").html(Babynews.email.strings.sendSuccessButton);b.append(a);c.html(b);Babynews.ga.reportEvent("Sharing","email sent",j+" : "+e)}a.click(function(l){jQuery(l.target).parents("#emailUI").fadeOut(300,function(){jQuery(this).replaceWith(Babynews.email.getUI(jQuery(this).attr("key")))})})}}},
strings:{errorButton:"Try sending again",sendSuccessText:"Your email has been sent.",sendSuccessButton:"OK",senderPrompt:"your name or email",recipientPrompt:"recipient's email"},getUI:function(a){var c=jQuery("<div>");c.attr("id","emailUI");c.attr("key",a);var d=jQuery("<form>").attr("id","emailForm"),b=jQuery("<input>").addClass("shareInput").attr("type","text").val(Babynews.email.strings.senderPrompt).attr("name","from"),e=jQuery("<input>").addClass("shareInput").attr("type","text").val(Babynews.email.strings.recipientPrompt).attr("name",
"to");a=jQuery("<input>").attr("type","hidden").val(a).attr("name","key");var j=jQuery("<input>").attr("type","submit").val("send").attr("id","submit");b.focus(function(){if(this.value==Babynews.email.strings.senderPrompt)this.value=""});e.focus(function(){if(this.value==Babynews.email.strings.recipientPrompt)this.value=""});d.append(b);d.append(e);d.append(a);d.append(j);d.submit(Babynews.email.sendEmail);c.append(d);return c}};
Babynews.bitly={shortenURL:function(a,c,d){if(Babynews.bitly.requests==null)Babynews.bitly.requests=[];a={post:a,callback:d,element:c};Babynews.bitly.requests.push(a);Babynews.bitly.send(a)},send:function(a){BitlyClient.shorten(a.post.post_url,"Babynews.bitly.response")},response:function(a){var c=null;if(!(a==null||a.results==null)){for(var d in Babynews.bitly.requests)if(this.requests[d].post.post_url in a.results){c=this.requests.splice(d,1)[0];break}a=a.results[c.post.post_url].shortUrl;c.callback!=
null&&c.callback(c.post,c.element,a)}}};Babynews.linkify=function(a,c){var d="";d=/(\b(https?|ftp):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim;d=c?a.replace(d,'<a class="moreLink" href="$1" target="_blank">more</a>'):a.replace(d,'<span class="inlineLink"><a class="inlineLink" href="$1" target="_blank">$1</a></span>');var b=/(^|[^\/])(www\.[\S]+(\b|$))/gim;return d=c?d.replace(b,'<a class="moreLink" href="http://$2" target="_blank">more</a>'):d.replace(b,'<span class="inlineLink">$1<a href="http://$2" target="_blank">$2</a></span>')};
Babynews.makeRefer=function(a){return Babynews.settings.BASE_URL+"refer="+a};Babynews.moreClicked=function(a){var c=jQuery(a.target).attr("title");a=jQuery(a.target).attr("blog");Babynews.ga.reportEvent("Post Click","More",a+" : "+c)};
Babynews.trimtoRect2=function(a,c,d,b,e,j){if(!(a==null||a.length<1)){c=a.text();var k="";a.hasClass("fixHeadlineText");a.hasClass("fixContentText");var p=c;if(j)p=c+b;a.html(p);a.outerHeight();if(a.outerHeight()>d){p=j=Math.pow(2,Math.floor(Math.log(c.length)/Math.LN2));do{p/=2;a.html(c.substr(0,j)+b);j+=a.outerHeight()>d?-p:p}while(p>=1);if(e){for(;c.substr(--j,1)!=" "&&j>=0;);for(;!/[A-Za-z]/.test(c.substr(j-1,1))&&j>=0;)j--}k+=b;c=c.substr(0,j)}c=Babynews.linkify(c,false);c+=k;a.html(c)}};
Babynews.prettyDate=function(a){a/=1E3;var c=Math.floor(a/86400);if(!(isNaN(c)||c<0||c>=365))return c==0&&(a<60&&"less than 1 minute ago"||a<120&&"about 1 minute ago"||a<3600&&"about "+Math.floor(a/60)+" minutes ago"||a<7200&&"about 1 hour ago"||a<86400&&"about "+Math.floor(a/3600)+" hours ago")||c==1&&"Yesterday"||c<7&&c+" days ago"||c<365&&Math.ceil(c/7)+" weeks ago"};
Babynews.loadPlugins=function(){eval(function(a,c,d,b,e,j){e=function(k){return(k<c?"":e(parseInt(k/c)))+((k%=c)>35?String.fromCharCode(k+29):k.toString(36))};if(!"".replace(/^/,String)){for(;d--;)j[e(d)]=b[d]||e(d);b=[function(k){return j[k]}];e=function(){return"\\w+"};d=1}for(;d--;)if(b[d])a=a.replace(new RegExp("\\b"+e(d)+"\\b","g"),b[d]);return a}('(5($){5 H(a){a.1D.1f[a.1E]=1F(a.1G,10)+a.1H}6 j=5(a){1I({1J:"1g.Z.1K 1L 1M",1N:a})};6 k=5(){7(/*@1O!@*/11&&(1P 1Q.1h.1f.1R==="1S"))};6 l={1T:[0,4,4],1U:[1i,4,4],1V:[1j,1j,1W],1X:[0,0,0],1Y:[0,0,4],1Z:[1k,1l,1l],20:[0,4,4],21:[0,0,A],22:[0,A,A],23:[12,12,12],24:[0,13,0],26:[27,28,1m],29:[A,0,A],2a:[2b,1m,2c],2d:[4,1n,0],2e:[2f,2g,2h],2i:[A,0,0],2j:[2k,2l,2m],2n:[2o,0,R],2p:[4,0,4],2q:[4,2r,0],2s:[0,t,0],2t:[2u,0,2v],2w:[1i,1o,1n],2x:[2y,2z,1o],2A:[1p,4,4],2B:[1q,2C,1q],2D:[R,R,R],2E:[4,2F,2G],2H:[4,4,1p],2I:[0,4,0],2J:[4,0,4],2K:[t,0,0],2L:[0,0,t],2M:[t,t,0],2N:[4,1k,0],2O:[4,S,2P],2Q:[t,0,t],2R:[t,0,t],2S:[4,0,0],2T:[S,S,S],2U:[4,4,4],2V:[4,4,0],9:[4,4,4]};6 m=5(a){T(a&&a.1r("#")==-1&&a.1r("(")==-1){7"2W("+l[a].2X()+")"}2Y{7 a}};$.2Z($.30.31,{u:H,v:H,w:H,x:H});$.1s.32=5(){7 U.1t(5(){6 a=$(U);a.Z(a.B(\'1u\'))})};$.1s.Z=5(i){7 U.1t(5(){6 c=$(U),3,$8,C,14,15,16=k();T(c.B(\'V\')){7 11}6 e={I:(5(a){33(a){W"X":7"Y";W"Y":7"X";W"17":7"18";W"18":7"17";34:7"Y"}})(i.I),y:m(i.D)||"#E",D:m(i.y)||c.z("19-D"),1v:c.J(),F:i.F||1w,K:i.K||5(){},L:i.L||5(){},M:i.M||5(){}};c.B(\'1u\',e).B(\'V\',1).B(\'35\',e);3={s:c.s(),n:c.n(),y:m(i.y)||c.z("19-D"),1x:c.z("36-37")||"38",I:i.I||"X",G:m(i.D)||"#E",F:i.F||1w,o:c.1y().o,p:c.1y().p,1z:i.1v||39,9:"9",1a:i.1a||11,K:i.K||5(){},L:i.L||5(){},M:i.M||5(){}};16&&(3.9="#3a");$8=c.z("1b","3b").8(3c).B(\'V\',1).3d("1h").J("").z({1b:"1A",3e:"3f",p:3.p,o:3.o,3g:0,3h:3i});6 f=5(){7{1B:3.9,1x:0,3j:0,u:0,w:0,x:0,v:0,N:3.9,O:3.9,P:3.9,Q:3.9,19:"3k",3l:\'3m\',n:0,s:0}};6 g=5(){6 a=(3.n/13)*25;6 b=f();b.s=3.s;7{"q":b,"1c":{u:0,w:a,x:a,v:0,N:\'#E\',O:\'#E\',o:(3.o+(3.n/2)),p:(3.p-a)},"r":{v:0,u:0,w:0,x:0,N:3.9,O:3.9,o:3.o,p:3.p}}};6 h=5(){6 a=(3.n/13)*25;6 b=f();b.n=3.n;7{"q":b,"1c":{u:a,w:0,x:0,v:a,P:\'#E\',Q:\'#E\',o:3.o-a,p:3.p+(3.s/2)},"r":{u:0,w:0,x:0,v:0,P:3.9,Q:3.9,o:3.o,p:3.p}}};14={"X":5(){6 d=g();d.q.u=3.n;d.q.N=3.y;d.r.v=3.n;d.r.O=3.G;7 d},"Y":5(){6 d=g();d.q.v=3.n;d.q.O=3.y;d.r.u=3.n;d.r.N=3.G;7 d},"17":5(){6 d=h();d.q.w=3.s;d.q.P=3.y;d.r.x=3.s;d.r.Q=3.G;7 d},"18":5(){6 d=h();d.q.x=3.s;d.q.Q=3.y;d.r.w=3.s;d.r.P=3.G;7 d}};C=14[3.I]();16&&(C.q.3n="3o(D="+3.9+")");15=5(){6 a=3.1z;7 a&&a.1g?a.J():a};$8.1d(5(){3.K($8,c);$8.J(\'\').z(C.q);$8.1e()});$8.1C(C.1c,3.F);$8.1d(5(){3.M($8,c);$8.1e()});$8.1C(C.r,3.F);$8.1d(5(){T(!3.1a){c.z({1B:3.G})}c.z({1b:"1A"});6 a=15();T(a){c.J(a)}$8.3p();3.L($8,c);c.3q(\'V\');$8.1e()})})}})(3r);',
62,214,"|||flipObj|255|function|var|return|clone|transparent||||||||||||||height|top|left|start|second|width|128|borderTopWidth|borderBottomWidth|borderLeftWidth|borderRightWidth|bgColor|css|139|data|dirOption|color|999|speed|toColor|int_prop|direction|html|onBefore|onEnd|onAnimation|borderTopColor|borderBottomColor|borderLeftColor|borderRightColor|211|192|if|this|flipLock|case|tb|bt|flip||false|169|100|dirOptions|newContent|ie6|lr|rl|background|dontChangeColor|visibility|first|queue|dequeue|style|jquery|body|240|245|165|42|107|140|230|224|144|indexOf|fn|each|flipRevertedSettings|content|500|fontSize|offset|target|visible|backgroundColor|animate|elem|prop|parseInt|now|unit|throw|name|js|plugin|error|message|cc_on|typeof|document|maxHeight|undefined|aqua|azure|beige|220|black|blue|brown|cyan|darkblue|darkcyan|darkgrey|darkgreen||darkkhaki|189|183|darkmagenta|darkolivegreen|85|47|darkorange|darkorchid|153|50|204|darkred|darksalmon|233|150|122|darkviolet|148|fuchsia|gold|215|green|indigo|75|130|khaki|lightblue|173|216|lightcyan|lightgreen|238|lightgrey|lightpink|182|193|lightyellow|lime|magenta|maroon|navy|olive|orange|pink|203|purple|violet|red|silver|white|yellow|rgb|toString|else|extend|fx|step|revertFlip|switch|default|flipSettings|font|size|12px|null|123456|hidden|true|appendTo|position|absolute|margin|zIndex|9999|lineHeight|none|borderStyle|solid|filter|chroma|remove|removeData|jQuery".split("|"),
0,{}));jQuery.fn.extend({everyTime:function(a,c,d,b){return this.each(function(){jQuery.timer.add(this,a,c,d,b)})},oneTime:function(a,c,d){return this.each(function(){jQuery.timer.add(this,a,c,d,1)})},stopTime:function(a,c){return this.each(function(){jQuery.timer.remove(this,a,c)})}});jQuery.extend({timer:{global:[],guid:1,dataKey:"jQuery.timer",regex:/^([0-9]+(?:\.[0-9]*)?)\s*(.*s)?$/,powers:{ms:1,cs:10,ds:100,s:1E3,das:1E4,hs:1E5,ks:1E6},timeParse:function(a){if(a==undefined||a==null)return null;
var c=this.regex.exec(jQuery.trim(a.toString()));return c[2]?parseFloat(c[1])*(this.powers[c[2]]||1):a},add:function(a,c,d,b,e){var j=0;if(jQuery.isFunction(d)){e||(e=b);b=d;d=c}c=jQuery.timer.timeParse(c);if(!(typeof c!="number"||isNaN(c)||c<0)){if(typeof e!="number"||isNaN(e)||e<0)e=0;e=e||0;var k=jQuery.data(a,this.dataKey)||jQuery.data(a,this.dataKey,{});k[d]||(k[d]={});b.timerID=b.timerID||this.guid++;var p=function(){if(++j>e&&e!==0||b.call(a,j)===false)jQuery.timer.remove(a,d,b)};p.timerID=
b.timerID;k[d][b.timerID]||(k[d][b.timerID]=window.setInterval(p,c));this.global.push(a)}},remove:function(a,c,d){var b=jQuery.data(a,this.dataKey),e;if(b){if(c){if(b[c]){if(d){if(d.timerID){window.clearInterval(b[c][d.timerID]);delete b[c][d.timerID]}}else for(d in b[c]){window.clearInterval(b[c][d]);delete b[c][d]}for(e in b[c])break;if(!e){e=null;delete b[c]}}}else for(c in b)this.remove(a,c,d);for(e in b)break;e||jQuery.removeData(a,this.dataKey)}}}});jQuery(window).bind("unload",function(){jQuery.each(jQuery.timer.global,
function(a,c){jQuery.timer.remove(c)})});(function(a){a.extend({base64Encode:function(c){var d="",b,e,j,k,p,l,q=0;c=c;c=c.replace(/\x0d\x0a/g,"\n");e="";for(j=0;j<c.length;j++){k=c.charCodeAt(j);if(k<128)e+=String.fromCharCode(k);else{if(k>127&&k<2048)e+=String.fromCharCode(k>>6|192);else{e+=String.fromCharCode(k>>12|224);e+=String.fromCharCode(k>>6&63|128)}e+=String.fromCharCode(k&63|128)}}for(c=e;q<c.length;){b=c.charCodeAt(q++);e=c.charCodeAt(q++);j=c.charCodeAt(q++);k=b>>2;b=(b&3)<<4|e>>4;p=(e&
15)<<2|j>>6;l=j&63;if(isNaN(e))p=l=64;else if(isNaN(j))l=64;d=d+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l)}return d},base64Decode:function(c){var d="",b,e,j,k,p,l,q=0;for(c=c.replace(/[^A-Za-z0-9\+\/\=]/g,"");q<c.length;){j="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(q++));
k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(q++));p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(q++));l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(q++));b=(k&15)<<4|p>>2;e=(p&3)<<6|l;d+=String.fromCharCode(j<<2|k>>4);if(p!=64)d+=String.fromCharCode(b);if(l!=64)d+=String.fromCharCode(e)}c=d;d="";for(e=c1=c2=b=0;b<c.length;){e=c.charCodeAt(b);if(e<128){d+=String.fromCharCode(e);
b++}else if(e>191&&e<224){c2=c.charCodeAt(b+1);d+=String.fromCharCode((e&31)<<6|c2&63);b+=2}else{c2=c.charCodeAt(b+1);c3=c.charCodeAt(b+2);d+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63);b+=3}}return d}})})(jQuery);(function(a){var c,d,b,e,j,k,p,l,q,s=0,g={},n=[],o=0,h={},t=[],D=null,z=new Image,H=/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i,T=/[^\.]\.(swf)\s*$/i,I,J=1,v,w,u=false,E=a.extend(a("<div/>")[0],{prop:0}),B=0,P=!a.support.opacity&&!window.XMLHttpRequest,K=function(){d.hide();z.onerror=z.onload=
null;D&&D.abort();c.empty()},Q=function(){a.fancybox('<p id="fancybox_error">The requested content cannot be loaded.<br />Please try again later.</p>',{scrolling:"no",padding:20,transitionIn:"none",transitionOut:"none"})},L=function(){return[a(window).width(),a(window).height(),a(document).scrollLeft(),a(document).scrollTop()]},U=function(){var f=L(),m={},r=h.margin,x=h.autoScale,A=(20+r)*2,C=(20+r)*2,y=h.padding*2;if(h.width.toString().indexOf("%")>-1){m.width=f[0]*parseFloat(h.width)/100-40;x=false}else m.width=
h.width+y;if(h.height.toString().indexOf("%")>-1){m.height=f[1]*parseFloat(h.height)/100-40;x=false}else m.height=h.height+y;if(x&&(m.width>f[0]-A||m.height>f[1]-C))if(g.type=="image"||g.type=="swf"){A+=y;C+=y;x=Math.min(Math.min(f[0]-A,h.width)/h.width,Math.min(f[1]-C,h.height)/h.height);m.width=Math.round(x*(m.width-y))+y;m.height=Math.round(x*(m.height-y))+y}else{m.width=Math.min(m.width,f[0]-A);m.height=Math.min(m.height,f[1]-C)}m.top=f[3]+(f[1]-(m.height+40))*0.5;m.left=f[2]+(f[0]-(m.width+40))*
0.5;if(h.autoScale===false){m.top=Math.max(f[3]+r,m.top);m.left=Math.max(f[2]+r,m.left)}return m},V=function(f){if(f&&f.length)switch(h.titlePosition){case "inside":return f;case "over":return'<span id="fancybox-title-over">'+f+"</span>";default:return'<span id="fancybox-title-wrap"><span id="fancybox-title-left"></span><span id="fancybox-title-main">'+f+'</span><span id="fancybox-title-right"></span></span>'}return false},W=function(){var f=h.title,m=w.width-h.padding*2,r="fancybox-title-"+h.titlePosition;
a("#fancybox-title").remove();B=0;if(h.titleShow!==false){f=a.isFunction(h.titleFormat)?h.titleFormat(f,t,o,h):V(f);if(!(!f||f==="")){a('<div id="fancybox-title" class="'+r+'" />').css({width:m,paddingLeft:h.padding,paddingRight:h.padding}).html(f).appendTo("body");switch(h.titlePosition){case "inside":B=a("#fancybox-title").outerHeight(true)-h.padding;w.height+=B;break;case "over":a("#fancybox-title").css("bottom",h.padding);break;default:a("#fancybox-title").css("bottom",a("#fancybox-title").outerHeight(true)*
-1);break}a("#fancybox-title").appendTo(j).hide()}}},X=function(){a(document).unbind("keydown.fb").bind("keydown.fb",function(f){if(f.keyCode==27&&h.enableEscapeButton){f.preventDefault();a.fancybox.close()}else if(f.keyCode==37){f.preventDefault();a.fancybox.prev()}else if(f.keyCode==39){f.preventDefault();a.fancybox.next()}});if(a.fn.mousewheel){e.unbind("mousewheel.fb");t.length>1&&e.bind("mousewheel.fb",function(f,m){f.preventDefault();u||m===0||(m>0?a.fancybox.prev():a.fancybox.next())})}if(h.showNavArrows){if(h.cyclic&&
t.length>1||o!==0)l.show();if(h.cyclic&&t.length>1||o!=t.length-1)q.show()}},M=function(){k.css("overflow",h.scrolling=="auto"?h.type=="image"||h.type=="iframe"||h.type=="swf"?"hidden":"auto":h.scrolling=="yes"?"auto":"visible");if(!a.support.opacity){k.get(0).style.removeAttribute("filter");e.get(0).style.removeAttribute("filter")}a("#fancybox-title").show();h.hideOnContentClick&&k.one("click",a.fancybox.close);h.hideOnOverlayClick&&b.one("click",a.fancybox.close);h.showCloseButton&&p.show();X();
a(window).bind("resize.fb",a.fancybox.center);h.centerOnScroll?a(window).bind("scroll.fb",a.fancybox.center):a(window).unbind("scroll.fb");a.isFunction(h.onComplete)&&h.onComplete(t,o,h);u=false;var f,m;if(t.length-1>o){f=t[o+1].href;if(typeof f!=="undefined"&&f.match(H)){m=new Image;m.src=f}}if(o>0){f=t[o-1].href;if(typeof f!=="undefined"&&f.match(H)){m=new Image;m.src=f}}},N=function(f){var m=Math.round(v.width+(w.width-v.width)*f),r=Math.round(v.height+(w.height-v.height)*f);e.css({width:m+"px",
height:r+"px",top:Math.round(v.top+(w.top-v.top)*f)+"px",left:Math.round(v.left+(w.left-v.left)*f)+"px"});m=Math.max(m-h.padding*2,0);r=Math.max(r-(h.padding*2+B*f),0);k.css({width:m+"px",height:r+"px"});if(typeof w.opacity!=="undefined")e.css("opacity",f<0.5?0.5:f)},R=function(){var f=g.orig?a(g.orig):false,m={};if(f&&f.length){f=f;m=f.offset();m.top+=parseFloat(f.css("paddingTop"))||0;m.left+=parseFloat(f.css("paddingLeft"))||0;m.top+=parseFloat(f.css("border-top-width"))||0;m.left+=parseFloat(f.css("border-left-width"))||
0;m.width=f.width();m.height=f.height();f=m;m={width:f.width+h.padding*2,height:f.height+h.padding*2,top:f.top-h.padding-20,left:f.left-h.padding-20}}else{f=L();m={width:1,height:1,top:f[3]+f[1]*0.5,left:f[2]+f[0]*0.5}}return m},O=function(){d.hide();if(e.is(":visible")&&a.isFunction(h.onCleanup))if(h.onCleanup(t,o,h)===false){a.event.trigger("fancybox-cancel");u=false;return}t=n;o=s;h=g;k.get(0).scrollTop=0;k.get(0).scrollLeft=0;if(h.overlayShow){P&&a("select:not(#fancybox-tmp select)").filter(function(){return this.style.visibility!==
"hidden"}).css({visibility:"hidden"}).one("fancybox-cleanup",function(){this.style.visibility="inherit"});b.css({"background-color":h.overlayColor,opacity:h.overlayOpacity}).unbind().show()}w=U();W();if(e.is(":visible")){a(p.add(l).add(q)).hide();var f=e.position(),m;v={top:f.top,left:f.left,width:e.width(),height:e.height()};m=v.width==w.width&&v.height==w.height;k.fadeOut(h.changeFade,function(){var r=function(){k.html(c.contents()).fadeIn(h.changeFade,M)};a.event.trigger("fancybox-change");k.empty().css("overflow",
"hidden");if(m){k.css({top:h.padding,left:h.padding,width:Math.max(w.width-h.padding*2,1),height:Math.max(w.height-h.padding*2-B,1)});r()}else{k.css({top:h.padding,left:h.padding,width:Math.max(v.width-h.padding*2,1),height:Math.max(v.height-h.padding*2,1)});E.prop=0;a(E).animate({prop:1},{duration:h.changeSpeed,easing:h.easingChange,step:N,complete:r})}})}else{e.css("opacity",1);if(h.transitionIn=="elastic"){v=R();k.css({top:h.padding,left:h.padding,width:Math.max(v.width-h.padding*2,1),height:Math.max(v.height-
h.padding*2,1)}).html(c.contents());e.css(v).show();if(h.opacity)w.opacity=0;E.prop=0;a(E).animate({prop:1},{duration:h.speedIn,easing:h.easingIn,step:N,complete:M})}else{k.css({top:h.padding,left:h.padding,width:Math.max(w.width-h.padding*2,1),height:Math.max(w.height-h.padding*2-B,1)}).html(c.contents());e.css(w).fadeIn(h.transitionIn=="none"?0:h.speedIn,M)}}},G=function(){c.width(g.width);c.height(g.height);if(g.width=="auto")g.width=c.width();if(g.height=="auto")g.height=c.height();O()},F=function(){K();
var f=n[s],m,r,x,A,C;g=a.extend({},a.fn.fancybox.defaults,typeof a(f).data("fancybox")=="undefined"?g:a(f).data("fancybox"));x=f.title||a(f).title||g.title||"";if(f.nodeName&&!g.orig)g.orig=a(f).children("img:first").length?a(f).children("img:first"):a(f);if(x===""&&g.orig)x=g.orig.attr("alt");m=f.nodeName&&/^(?:javascript|#)/i.test(f.href)?g.href||null:g.href||f.href||null;if(g.type){r=g.type;if(!m)m=g.content}else if(g.content)r="html";else if(m)if(m.match(H))r="image";else if(m.match(T))r="swf";
else if(a(f).hasClass("iframe"))r="iframe";else if(m.match(/#/)){f=m.substr(m.indexOf("#"));r=a(f).length>0?"inline":"ajax"}else r="ajax";else r="inline";g.type=r;g.href=m;g.title=x;if(g.autoDimensions&&g.type!=="iframe"&&g.type!=="swf"){g.width="auto";g.height="auto"}if(g.modal){g.overlayShow=true;g.hideOnOverlayClick=false;g.hideOnContentClick=false;g.enableEscapeButton=false;g.showCloseButton=false}if(a.isFunction(g.onStart))if(g.onStart(n,s,g)===false){u=false;return}c.css("padding",20+g.padding+
g.margin);a(".fancybox-inline-tmp").unbind("fancybox-cancel").bind("fancybox-change",function(){a(this).replaceWith(k.children())});switch(r){case "html":c.html(g.content);G();break;case "inline":a('<div class="fancybox-inline-tmp" />').hide().insertBefore(a(f)).bind("fancybox-cleanup",function(){a(this).replaceWith(k.children())}).bind("fancybox-cancel",function(){a(this).replaceWith(c.children())});a(f).appendTo(c);G();break;case "image":u=false;a.fancybox.showActivity();z=new Image;z.onerror=function(){Q()};
z.onload=function(){z.onerror=null;z.onload=null;u=true;g.width=z.width;g.height=z.height;a("<img />").attr({id:"fancybox-img",src:z.src,alt:g.title}).appendTo(c);O()};z.src=m;break;case "swf":A='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+g.width+'" height="'+g.height+'"><param name="movie" value="'+m+'"></param>';C="";a.each(g.swf,function(y,S){A+='<param name="'+y+'" value="'+S+'"></param>';C+=" "+y+'="'+S+'"'});A+='<embed src="'+m+'" type="application/x-shockwave-flash" width="'+
g.width+'" height="'+g.height+'"'+C+"></embed></object>";c.html(A);G();break;case "ajax":f=m.split("#",2);r=g.ajax.data||{};if(f.length>1){m=f[0];if(typeof r=="string")r+="&selector="+f[1];else r.selector=f[1]}u=false;a.fancybox.showActivity();D=a.ajax(a.extend(g.ajax,{url:m,data:r,error:Q,success:function(y){if(D.status==200){c.html(y);G()}}}));break;case "iframe":a('<iframe id="fancybox-frame" name="fancybox-frame'+(new Date).getTime()+'" frameborder="0" hspace="0" scrolling="'+g.scrolling+'" src="'+
g.href+'"></iframe>').appendTo(c);O();break}},Y=function(){if(d.is(":visible")){a("div",d).css("top",J*-40+"px");J=(J+1)%12}else clearInterval(I)},Z=function(){if(!a("#fancybox-wrap").length){a("body").append(c=a('<div id="fancybox-tmp"></div>'),d=a('<div id="fancybox-loading"><div></div></div>'),b=a('<div id="fancybox-overlay"></div>'),e=a('<div id="fancybox-wrap"></div>'));if(!a.support.opacity){e.addClass("fancybox-ie");d.addClass("fancybox-ie")}j=a('<div id="fancybox-outer"></div>').append('<div class="fancy-bg" id="fancy-bg-n"></div><div class="fancy-bg" id="fancy-bg-ne"></div><div class="fancy-bg" id="fancy-bg-e"></div><div class="fancy-bg" id="fancy-bg-se"></div><div class="fancy-bg" id="fancy-bg-s"></div><div class="fancy-bg" id="fancy-bg-sw"></div><div class="fancy-bg" id="fancy-bg-w"></div><div class="fancy-bg" id="fancy-bg-nw"></div>').appendTo(e);
j.append(k=a('<div id="fancybox-inner"></div>'),p=a('<a id="fancybox-close"></a>'),l=a('<a href="javascript:;" id="fancybox-left"><span class="fancy-ico" id="fancybox-left-ico"></span></a>'),q=a('<a href="javascript:;" id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a>'));p.click(a.fancybox.close);d.click(a.fancybox.cancel);l.click(function(f){f.preventDefault();a.fancybox.prev()});q.click(function(f){f.preventDefault();a.fancybox.next()});if(P){b.get(0).style.setExpression("height",
"document.body.scrollHeight > document.body.offsetHeight ? document.body.scrollHeight : document.body.offsetHeight + 'px'");d.get(0).style.setExpression("top","(-20 + (document.documentElement.clientHeight ? document.documentElement.clientHeight/2 : document.body.clientHeight/2 ) + ( ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop )) + 'px'");j.prepend('<iframe id="fancybox-hide-sel-frame" src="javascript:\'\';" scrolling="no" frameborder="0" ></iframe>')}}};
a.fn.fancybox=function(f){a(this).data("fancybox",a.extend({},f,a.metadata?a(this).metadata():{})).unbind("click.fb").bind("click.fb",function(m){m.preventDefault();if(!u){u=true;a(this).blur();n=[];s=0;m=a(this).attr("rel")||"";if(!m||m==""||m==="nofollow")n.push(this);else{n=a("a[rel="+m+"], area[rel="+m+"]");s=n.index(this)}F();return false}});return this};a.fancybox=function(f,m){if(!u){u=true;m=typeof m!=="undefined"?m:{};n=[];s=m.index||0;if(a.isArray(f)){for(var r=0,x=f.length;r<x;r++)if(typeof f[r]==
"object")a(f[r]).data("fancybox",a.extend({},m,f[r]));else f[r]=a({}).data("fancybox",a.extend({content:f[r]},m));n=jQuery.merge(n,f)}else{if(typeof f=="object")a(f).data("fancybox",a.extend({},m,f));else f=a({}).data("fancybox",a.extend({content:f},m));n.push(f)}if(s>n.length||s<0)s=0;F()}};a.fancybox.showActivity=function(){clearInterval(I);d.show();I=setInterval(Y,66)};a.fancybox.hideActivity=function(){d.hide()};a.fancybox.next=function(){return a.fancybox.pos(o+1)};a.fancybox.prev=function(){return a.fancybox.pos(o-
1)};a.fancybox.pos=function(f){if(!u){f=parseInt(f,10);if(f>-1&&t.length>f){s=f;F()}if(h.cyclic&&t.length>1&&f<0){s=t.length-1;F()}if(h.cyclic&&t.length>1&&f>=t.length){s=0;F()}}};a.fancybox.cancel=function(){if(!u){u=true;a.event.trigger("fancybox-cancel");K();g&&a.isFunction(g.onCancel)&&g.onCancel(n,s,g);u=false}};a.fancybox.close=function(){function f(){b.fadeOut("fast");e.hide();a.event.trigger("fancybox-cleanup");k.empty();a.isFunction(h.onClosed)&&h.onClosed(t,o,h);t=g=[];o=s=0;h=g={};u=false}
if(!(u||e.is(":hidden"))){u=true;if(h&&a.isFunction(h.onCleanup))if(h.onCleanup(t,o,h)===false){u=false;return}K();a(p.add(l).add(q)).hide();a("#fancybox-title").remove();e.add(k).add(b).unbind();a(window).unbind("resize.fb scroll.fb");a(document).unbind("keydown.fb");k.css("overflow","hidden");if(h.transitionOut=="elastic"){v=R();var m=e.position();w={top:m.top,left:m.left,width:e.width(),height:e.height()};if(h.opacity)w.opacity=1;E.prop=1;a(E).animate({prop:0},{duration:h.speedOut,easing:h.easingOut,
step:N,complete:f})}else e.fadeOut(h.transitionOut=="none"?0:h.speedOut,f)}};a.fancybox.resize=function(){var f,m;if(!(u||e.is(":hidden"))){u=true;f=k.wrapInner("<div style='overflow:auto'></div>").children();m=f.height();e.css({height:m+h.padding*2+B});k.css({height:m});f.replaceWith(f.children());a.fancybox.center()}};a.fancybox.center=function(){u=true;var f=L(),m=h.margin,r={};r.top=f[3]+(f[1]-(e.height()-B+40))*0.5;r.left=f[2]+(f[0]-(e.width()+40))*0.5;r.top=Math.max(f[3]+m,r.top);r.left=Math.max(f[2]+
m,r.left);e.css(r);u=false};a.fn.fancybox.defaults={padding:10,margin:20,opacity:false,modal:false,cyclic:false,scrolling:"auto",width:560,height:340,autoScale:true,autoDimensions:true,centerOnScroll:false,ajax:{},swf:{wmode:"transparent"},hideOnOverlayClick:true,hideOnContentClick:false,overlayShow:true,overlayOpacity:0.3,overlayColor:"#666",titleShow:true,titlePosition:"outside",titleFormat:null,transitionIn:"fade",transitionOut:"fade",speedIn:300,speedOut:300,changeSpeed:300,changeFade:"fast",
easingIn:"swing",easingOut:"swing",showCloseButton:true,showNavArrows:true,enableEscapeButton:true,onStart:null,onCancel:null,onComplete:null,onCleanup:null,onClosed:null};a(document).ready(function(){Z()})})(jQuery)};
var ZeroClipboard={version:"1.0.7",clients:{},moviePath:"ZeroClipboard.swf",nextId:1,$:function(a){if(typeof a=="string")a=document.getElementById(a);if(!a.addClass){a.hide=function(){this.style.display="none"};a.show=function(){this.style.display=""};a.addClass=function(c){this.removeClass(c);this.className+=" "+c};a.removeClass=function(c){for(var d=this.className.split(/\s+/),b=-1,e=0;e<d.length;e++)if(d[e]==c){b=e;e=d.length}if(b>-1){d.splice(b,1);this.className=d.join(" ")}return this};a.hasClass=
function(c){return!!this.className.match(new RegExp("\\s*"+c+"\\s*"))}}return a},setMoviePath:function(a){this.moviePath=a},dispatch:function(a,c,d){(a=this.clients[a])&&a.receiveEvent(c,d)},register:function(a,c){this.clients[a]=c},getDOMObjectPosition:function(a,c){for(var d={left:0,top:0,width:a.width?a.width:a.offsetWidth,height:a.height?a.height:a.offsetHeight};a&&a!=c;){d.left+=a.offsetLeft;d.top+=a.offsetTop;a=a.offsetParent}return d},Client:function(a){this.handlers={};this.id=ZeroClipboard.nextId++;
this.movieId="ZeroClipboardMovie_"+this.id;ZeroClipboard.register(this.id,this);a&&this.glue(a)}};
ZeroClipboard.Client.prototype={id:0,ready:false,movie:null,clipText:"",handCursorEnabled:true,cssEffects:true,handlers:null,glue:function(a,c,d){this.domElement=ZeroClipboard.$(a);a=99;if(this.domElement.style.zIndex)a=parseInt(this.domElement.style.zIndex,10)+1;if(typeof c=="string")c=ZeroClipboard.$(c);else if(typeof c=="undefined")c=document.getElementsByTagName("body")[0];var b=ZeroClipboard.getDOMObjectPosition(this.domElement,c);this.div=document.createElement("div");var e=this.div.style;e.position=
"absolute";e.left=""+b.left+"px";e.top=""+b.top+"px";e.width=""+b.width+"px";e.height=""+b.height+"px";e.zIndex=a;if(typeof d=="object")for(addedStyle in d)e[addedStyle]=d[addedStyle];c.appendChild(this.div);this.div.innerHTML=this.getHTML(b.width,b.height)},getHTML:function(a,c){var d="",b="id="+this.id+"&width="+a+"&height="+c;if(navigator.userAgent.match(/MSIE/)){var e=location.href.match(/^https/i)?"https://":"http://";d+='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+
e+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="'+a+'" height="'+c+'" id="'+this.movieId+'" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+ZeroClipboard.moviePath+'" /><param name="loop" value="false" /><param name="menu" value="false" /><param name="quality" value="best" /><param name="bgcolor" value="#ffffff" /><param name="flashvars" value="'+b+'"/><param name="wmode" value="transparent"/></object>'}else d+=
'<embed id="'+this.movieId+'" src="'+ZeroClipboard.moviePath+'" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="'+a+'" height="'+c+'" name="'+this.movieId+'" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="'+b+'" wmode="transparent" />';return d},hide:function(){if(this.div)this.div.style.left="-2000px"},show:function(){this.reposition()},destroy:function(){if(this.domElement&&
this.div){this.hide();this.div.innerHTML="";var a=document.getElementsByTagName("body")[0];try{a.removeChild(this.div)}catch(c){}this.div=this.domElement=null}},reposition:function(a){if(a)(this.domElement=ZeroClipboard.$(a))||this.hide();if(this.domElement&&this.div){a=ZeroClipboard.getDOMObjectPosition(this.domElement);var c=this.div.style;c.left=""+a.left+"px";c.top=""+a.top+"px"}},setText:function(a){this.clipText=a;this.ready&&this.movie.setText(a)},addEventListener:function(a,c){a=a.toString().toLowerCase().replace(/^on/,
"");this.handlers[a]||(this.handlers[a]=[]);this.handlers[a].push(c)},setHandCursor:function(a){this.handCursorEnabled=a;this.ready&&this.movie.setHandCursor(a)},setCSSEffects:function(a){this.cssEffects=!!a},receiveEvent:function(a,c){a=a.toString().toLowerCase().replace(/^on/,"");switch(a){case "load":this.movie=document.getElementById(this.movieId);if(!this.movie){var d=this;setTimeout(function(){d.receiveEvent("load",null)},1);return}if(!this.ready&&navigator.userAgent.match(/Firefox/)&&navigator.userAgent.match(/Windows/)){d=
this;setTimeout(function(){d.receiveEvent("load",null)},100);this.ready=true;return}this.ready=true;this.movie.setText(this.clipText);this.movie.setHandCursor(this.handCursorEnabled);break;case "mouseover":if(this.domElement&&this.cssEffects){this.domElement.addClass("hover");this.recoverActive&&this.domElement.addClass("active")}break;case "mouseout":if(this.domElement&&this.cssEffects){this.recoverActive=false;if(this.domElement.hasClass("active")){this.domElement.removeClass("active");this.recoverActive=
true}this.domElement.removeClass("hover")}break;case "mousedown":this.domElement&&this.cssEffects&&this.domElement.addClass("active");break;case "mouseup":if(this.domElement&&this.cssEffects){this.domElement.removeClass("active");this.recoverActive=false}break}if(this.handlers[a])for(var b=0,e=this.handlers[a].length;b<e;b++){var j=this.handlers[a][b];if(typeof j=="function")j(this,c);else if(typeof j=="object"&&j.length==2)j[0][j[1]](this,c);else typeof j=="string"&&window[j](this,c)}}};gadgets.util.registerOnLoadHandler(Babynews.init);